config/routes.rb
Rails.application.routes.draw do
	resources :lists
	resources :items

	root 'lists#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
	has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :set_item, only: [:edit, :show, :update, :destroy]

	def index
		@items = Item.all
	end

	def new
		@item = Item.new

		@lists = List.all
	end

	def create
		@item = Item.new(item_params)

		if @item.save
			redirect_to list_path(id: @item.list_id)
		else
			render :text => "Item not saved."
		end
		
	end
	
	def show

	end

	def edit
		@lists = List.all
	end

	def update
		if @item.state == "complete"
			@item.state = "active"
		else
			@item.state = "complete"
		end
		@item.save
		redirect_to list_path(id: @item.list_id)
	end

	def destroy
    @item.destroy
    redirect_to list_path(id: @item.list_id)
  end

	private

	def set_item
		@item = Item.find(params[:id])
	end

	def item_params
		params.require(:item).permit(:name, :quantity, :list_id, :state)		
	end


end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

	def index
		@lists = List.all		
	end

	def new
		@list = List.new
	end

	def create
		@list = List.new(list_params)

		if @list.save
			redirect_to :lists => :index
		else
			render :text => "List not saved."
		end
	end

	def show
		@list = List.find(params[:id])
		@items = Item.all
	end

	def edit
		@list = List.find(params[:id])
		@items = Item.all
	end

	def destroy
		@list = List.find(params[:id])
    @list.destroy
    redirect_to :lists
  end

private

	def list_params
		params.require(:list).permit(:name)		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/_form.html.erb
<%= form_for @item, url: {action: "create"} do |f| %>
	
<div class="form-group">
	<%= f.label :name %> <br>
	<%= f.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :quantity %> <br>
	<%= f.number_field :quantity, class: "form-control" %>
</div>

<div class="form-group">
	<%= f.label :list_id %> <br>
	<%= f.collection_select :list_id, @lists, :id, :name %> 
</div>


	<%= f.submit "Create Item", class: "btn btn-primary" %>
<% end %>

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<div class="panel panel-default">

	<div class="panel-heading">
		<h3><strong>Listing Items</strong></h3>
	</div>

	<div class="panel-body">
		<div class="row">
			<div class="col-md-4 bold">Item</div>
			<div class="col-md-4 bold">Quantity</div>
			<div class="col-md-4 bold">List</div>
		</div>
		<% @items.each do |item| %>
		<div class="row">
			<div class="col-md-4"><%= item.name %></div>
			<div class="col-md-4"><%= item.quantity %></div>
			<div class="col-md-4">
				<%= link_to item.list.name, list_path(item.list_id) %>
			</div>
		</div>
		<% end %>
	</div>
	
	<div class="panel-footer">
		<%= link_to "Add New Item", new_item_path, class: "btn btn-primary" %>
		<%= link_to "Add New List", new_list_path, class: "btn btn-primary" %>
	</div>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<h1>Show Item</h1>

<%= @item.name %>
<%= @item.quantity %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ShoppingList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= csrf_meta_tag %>
  <link href='https://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
</head>
<body>

	<nav class="navbar navbar-default" role="navigation">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Shopping Lists", root_path, class: "navbar-brand" %>
		</div>
	
		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "New List", new_list_path %></li>
				<li><%= link_to "New Item", new_item_path %></li>
				<li><%= link_to "All Lists", lists_path %></li>				
				<li><%= link_to "All Items", items_path %></li>				
			</ul>
		</div><!-- /.navbar-collapse -->
	</nav>

<div class="container">
<%= yield %>
</div>

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
   <!-- Latest compiled and minified JavaScript -->
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list, url: {action: "create"} do |f| %>
	
	<div class="form-group">
	<%= f.label :name %> <br>
	<%= f.text_field :name, class: "form-control" %>
	</div>
	<%= f.submit "Create List", class: "btn btn-primary" %>

<% end %>

<br>

app/views/lists/edit.html.erb
<h1>Edit List</h1>

<%= render 'form' %>

app/views/lists/index.html.erb
<div class="panel panel-default">

	<div class="panel-heading">
		<h3><strong>All Lists</strong></h3>
	</div>

	<div class="panel-body">
		<% @lists.each do |list| %>
			<%= link_to list.name, list %> <br>
		<% end %>
	</div>
	
	<div class="panel-footer">
		<%= link_to	"Add a new list", new_list_path, class: "btn btn-primary" %>
	</div>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to "Back", lists_path %>

app/views/lists/show.html.erb
<div class="panel panel-default">
		<div class="panel-heading">
			<h3><strong><%= @list.name %></strong></h3>
		</div>
		<div class="panel-body">
		<%= form_tag do %>
			<% @list.items.each do |item| %>
		<div class="row">
					<div class="col-md-2">
						<%= link_to check_box_tag(item), item, method: :put %>
						<%= label_tag(item, "#{item.name}: #{item.quantity}", class: item.state) %>
					</div>

				<div class="col-md-2">	
					<%= link_to "Delete Item", item, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-danger btn-xs" %>
				</div>
			</div>
			<% end %>
		<% end %>
	</div>

	<div class="panel-footer">
		<%= link_to "Add new item", new_item_path, class: "btn btn-primary" %>
		<%= link_to "Back", lists_path, class: "btn btn-primary" %>
		<%= link_to "Delete List", list_path, method: :delete,  data: {confirm: "Are you sure?" }, class: "btn btn-danger" %>
	</div>

</div>